openapi: 3.0.1
info:
  title: Traffic Light Controller API
  version: 1.0.0

paths:
  /api/traffic/status:
    get:
      summary: traffic status

  /api/traffic/sequence:
    post:
      summary: Sequence

  /api/traffic/pause:
    get:
      summary: Pause traffic

  /api/traffic/resume:
    get:
      summary: Resume traffic

  /api/traffic/history:
    get:
      summary: Get history